using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataModelLib.DataModels
{
	public class DatabaseModel : DataModel
	{

		public List<TableModel> TableModels
		{ 
			get; 
			private set; 
		}
		public string Namespace
		{
			get;
			private set;
		}
		public string DatabaseClassName
		{
			get;
			private set;
		}

		public DatabaseModel(string Namespace,string DatabaseClassName) : base()
		{
			TableModels = new List<TableModel>();
			this.Namespace = Namespace;this.DatabaseClassName = DatabaseClassName;
		}

		public override string GenerateDatabaseSource()
		{
			string source =
			$$"""
			// <auto-generated/>
			using System;
			using System.Collections.Generic;
			{{string.Join("\r\n", TableModels.Select(item => $"using {item.Namespace};").Distinct())}}
			
			namespace {{Namespace}}
			{
				public partial class {{DatabaseClassName}}
				{
			{{string.Join("\r\n", TableModels.Select(item => item.GenerateDatabaseSource())).Indent(2)}}

			{{this.GenerateDatabaseConstructorSource().Indent(2)}}
											
				}
			}
			""";

			return source;
		}

		public override string GenerateDatabaseConstructorSource()
		{
			string source =
			$$"""
			public {{DatabaseClassName}}()
			{
			{{string.Join("\r\n", TableModels.Select(item => item.GenerateDatabaseConstructorSource())).Indent(1)}}
			}
			""";

			return source;
		}

		public override string GenerateDatabaseModelSource()
		{
			string source =
			$$"""
			// <auto-generated/>
			using System;
			using System.Collections.Generic;
			{{string.Join("\r\n", TableModels.Select(item => $"using {item.Namespace};").Distinct()) }}

			namespace {{Namespace}}
			{
				public partial class {{DatabaseClassName}}Model
				{
					private {{DatabaseClassName}} dataSource;

					public {{DatabaseClassName}}Model({{DatabaseClassName}} DataSource)
					{
						this.dataSource=DataSource;
					}

			{{string.Join("\r\n", TableModels.Select(item=>item.GenerateDatabaseModelSource())).Indent(2)}}
				}
			}
			""";

			return source;
		}

	}
}
