using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataModelLib.Schema
{
	public class Database : SchemaObject
	{


		public string Namespace
		{
			get;
			private set;
		}
		public string DatabaseName
		{
			get;
			private set;
		}

		public List<Table> Tables
		{
			get;
			private set;
		}

		public Database(string Namespace,string DatabaseName) : base()
		{
			Tables = new List<Table>();
			this.Namespace = Namespace;this.DatabaseName = DatabaseName;
		}

		public string GenerateDatabaseClass()
		{
			string source =
			$$"""
			// <auto-generated/>
			using System;
			using System.Collections.Generic;
			{{string.Join("\r\n", Tables.Select(item => $"using {item.Namespace};").Distinct())}}
			
			namespace {{Namespace}}
			{
				public partial class {{DatabaseName}}
				{
			{{string.Join("\r\n", Tables.Select(item => item.GenerateDatabaseProperties())).Indent(2)}}

			{{this.GenerateDatabaseConstructor().Indent(2)}}
											
				}
			}
			""";

			return source;
		}

		public string GenerateDatabaseConstructor()
		{
			string source =
			$$"""
			public {{DatabaseName}}()
			{
			{{string.Join("\r\n", Tables.Select(item => item.GenerateDatabaseConstructor())).Indent(1)}}
			}
			""";

			return source;
		}

		public string GenerateDatabaseModelClass()
		{
			string source =
			$$"""
			// <auto-generated/>
			using System;
			using System.Collections.Generic;
			using System.Collections.Specialized;
			using System.Linq;
			using DataModelGenerator;
			{{string.Join("\r\n", Tables.Select(item => $"using {item.Namespace};").Distinct()) }}

			namespace {{Namespace}}
			{
				public partial class {{DatabaseName}}Model
				{
			{{string.Join("\r\n", Tables.Select(item => $"public event TableChangedEventHandler<{item.TableName}> {item.TableName}TableChanged;")).Indent(2)}}
			{{string.Join("\r\n", Tables.Select(item => $"public event RowChangedEventHandler<{item.TableName}> {item.TableName}RowChanged;")).Indent(2)}}
								
			
					private {{DatabaseName}} dataSource;

			{{this.GenerateDatabaseModelConstructor().Indent(2)}}
			
			{{string.Join("\r\n", Tables.Select(item=>item.GenerateDatabaseModelMethods())).Indent(2)}}
				}
			}
			""";

			return source;
		}
		public string GenerateDatabaseModelConstructor()
		{
			string source =
			$$"""
			public {{DatabaseName}}Model({{DatabaseName}} DataSource)
			{
				this.dataSource=DataSource;
			}
			""";

			return source;
		}


	}
}
